version: '3'

volumes:
  rethinkdb:
  storage-temp:

services:
  nginx:
    build: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api

  rethinkdb:
    image: rethinkdb:2.4
    restart: unless-stopped
    volumes:
      - rethinkdb:/data
    ports:
      - 7080:8080

  app:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf app --auth-url http://${PUBLIC_IP}/auth/oauth/ --websocket-url ws://${PUBLIC_IP}/ --port 3000
    depends_on:
      - rethinkdb
      - auth
      - websocket

  # auth:
  #   image: devicefarmer/stf:latest
  #   restart: unless-stopped
  #   environment:
  #     - RETHINKDB_PORT_28015_TCP
  #     - SECRET
  #   command: stf auth-mock --app-url http://${PUBLIC_IP}/ --port 3000
  #   depends_on:
  #     - rethinkdb

  auth:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
      - OAUTH_AUTHORIZATION_URL=https://staffpass.com/oauth2/auth.phtml
      - OAUTH_TOKEN_URL=https://staffpass.com/oauth2/token.phtml
      - OAUTH_USERINFO_URL=https://staffpass.com/oauth2/base-info.phtml
      - OAUTH_CLIENT_ID=devicefarmer
      - OAUTH_CLIENT_SECRET=+yEeZd3YmyjviqUPv9n1LZ+mP3A2/+3YHfvCPQHxNtrpt4fUlxm7
      - OAUTH_CALLBACK_URL=http://${PUBLIC_IP}/auth/oauth/callback
      - OAUTH_SCOPE="base-info"
    command: stf auth-oauth2 --app-url http://${PUBLIC_IP}/ --port 3000
    depends_on:
      - rethinkdb

  processor:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - ZMQ_TCP_KEEPALIVE=1
      - ZMQ_TCP_KEEPALIVE_IDLE=300
    command: stf processor --connect-app-dealer tcp://triproxy:7160 --connect-dev-dealer tcp://dev-triproxy:7260
    depends_on:
      - rethinkdb
      - triproxy
      - dev-triproxy
  triproxy:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
    environment:
      - ZMQ_TCP_KEEPALIVE=1
      - ZMQ_TCP_KEEPALIVE_IDLE=300
  dev-triproxy:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
    ports:
      - 7250:7250
      - 7260:7260
      - 7270:7270
    environment:
      - ZMQ_TCP_KEEPALIVE=1
      - ZMQ_TCP_KEEPALIVE_IDLE=300
  migrate:
    image: devicefarmer/stf:latest
    environment:
      - RETHINKDB_PORT_28015_TCP
      - STF_ADMIN_NAME=rajdeep.varma
      - STF_ADMIN_EMAIL=rajdeep.varma@team.bumble.com
    command: stf migrate
    depends_on:
      - rethinkdb
  reaper:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    depends_on:
      - migrate
      - rethinkdb
      - dev-triproxy
      - triproxy
    command: stf reaper dev --connect-push tcp://dev-triproxy:7270 --connect-sub tcp://triproxy:7150 --heartbeat-timeout 30000
  storage-plugin-apk:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf storage-plugin-apk --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-plugin-image:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf storage-plugin-image --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-temp:
    build: storage-temp/
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
    command: stf storage-temp --port 3000 --save-dir /app/data
  websocket:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
      - ZMQ_TCP_KEEPALIVE=1
      - ZMQ_TCP_KEEPALIVE_IDLE=300
    command: stf websocket --port 3000 --storage-url http://${PUBLIC_IP}/ --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170
    depends_on:
      - migrate
      - rethinkdb
      - storage-temp
      - triproxy
      - dev-triproxy
  api:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf api --port 3000 --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy

  group_engine:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf groups-engine --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy
      - dev-triproxy